#!/usr/bin/env python3
"""Download the latin subset of IBM Plex Sans/Mono and write assets/css/fonts.css.

The site self-hosts its fonts so it makes no third-party requests at all.
Re-run from the project root if the weights in use change:

    python3 tools/fetch-fonts.py
"""
import os
import re
import urllib.request

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=IBM+Plex+Mono:wght@400;500;600"
           "&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap")


def main() -> None:
    req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=30).read().decode()

    # Google emits one @font-face per subset, each preceded by a /* subset */
    # comment. The site is English-only, so everything but plain latin is waste.
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)

    os.makedirs("assets/fonts", exist_ok=True)
    faces, seen = [], set()
    for subset, block in blocks:
        if subset != "latin":
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        filename = f"{family.replace(' ', '')}-{weight}.woff2"
        if filename not in seen:
            seen.add(filename)
            urllib.request.urlretrieve(url, f"assets/fonts/{filename}")
            print(f"  {filename} ({os.path.getsize('assets/fonts/' + filename)} bytes)")

        unicode_range = re.search(r"unicode-range:([^;]+);", block)
        faces.append(
            "@font-face{\n"
            f"  font-family:'{family}';\n"
            f"  font-style:{style};\n"
            f"  font-weight:{weight};\n"
            "  font-display:swap;\n"
            f"  src:url('../fonts/{filename}') format('woff2');\n"
            + (f"  unicode-range:{unicode_range.group(1).strip()};\n" if unicode_range else "")
            + "}"
        )

    header = ("/* IBM Plex Sans + Mono, latin subset, self-hosted.\n"
              "   Generated by tools/fetch-fonts.py — do not edit by hand. */\n\n")
    with open("assets/css/fonts.css", "w") as fh:
        fh.write(header + "\n".join(faces) + "\n")
    print(f"\nwrote assets/css/fonts.css with {len(faces)} faces")


if __name__ == "__main__":
    main()
